language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install codecov coveralls
install:
  - pip install .
script: pytest --cov=pandas_datapackage_reader
after_success:
  - codecov
