language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install pytest pytest-cov geopandas
  - pip install codecov
install:
  - pip install .
script: pytest --cov
after_success:
  - codecov
