language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install pip --upgrade
install:
  - pip install -e .[tests]
script: pytest tests
