language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install pip --upgrade
  - pip install pytest pytest-cov geopandas
  - pip install codecov
install:
  - pip install .
script: pytest --cov
after_success:
  - codecov
